# Generated by Django 5.1.15 on 2026-05-13 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('slug', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('icon', models.CharField(blank=True, max_length=8)),
                ('color', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('slug', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('farm', models.CharField(max_length=160)),
                ('region', models.CharField(max_length=64)),
                ('years', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('deliveries', models.PositiveIntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('avatar', models.CharField(blank=True, max_length=8)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('litr', 'litr'), ('dona', 'dona')], default='kg', max_length=8)),
                ('price', models.PositiveIntegerField()),
                ('old_price', models.PositiveIntegerField(default=0)),
                ('min_order', models.PositiveIntegerField(default=10)),
                ('stock', models.PositiveIntegerField(default=100)),
                ('harvest', models.DateField(blank=True, null=True)),
                ('organic', models.BooleanField(default=False)),
                ('badge', models.CharField(blank=True, max_length=40)),
                ('img', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.farmer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
